on: [ push, pull_request, workflow_dispatch ]

permissions:
  contents: read

jobs:
  Test:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        brew install autoconf
        brew install automake
    - name: configure
      run: |
        autoreconf -iv
        ./configure
    - name: build
      run: |
        make


